# Generated by Django 4.0.6 on 2022-07-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('puesto', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('noinventario', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('noserie', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
